### ISSUE TITLE
magento-composer-installer + Error: Cannot find module 'gulp'

### ISSUE THREAD

**Issue by klierik** [Cotya/magento-composer-installer#39]
Good day.

I`m develope theme as module for Magento:
```
.
├── README.md
├── app
├── composer.json
├── gulpconfig.js
├── gulpfile.js
├── modman
├── package.json
└── skin
```

So my `composer.js` file contain require:
```
    "require": {
        "twbs/bootstrap-sass": "*",
        "magento-hackathon/magento-composer-installer": "3.0.2"
    },
```

When i`m try use my composer module i have problem with gulp. MCI (Magento Composer Installer) work good and i see how it create symlinks for all my files:
```
drwxr-x---@ 34 aleksej  staff   1.1K Jul  6 13:23 .
drwxr-xr-x   9 aleksej  staff   306B Jul  3 19:08 ..

lrwxr-xr-x   1 aleksej  staff    49B Jul  3 19:08 gulpconfig.js -> ../vendor/mavenecommerce/mbootstrap/gulpconfig.js
lrwxr-xr-x   1 aleksej  staff    47B Jul  3 19:08 gulpfile.js -> ../vendor/mavenecommerce/mbootstrap/gulpfile.js
drwxr-xr-x  17 aleksej  staff   578B Jul  3 19:09 node_modules
lrwxr-xr-x   1 aleksej  staff    48B Jul  3 19:08 package.json -> ../vendor/mavenecommerce/mbootstrap/package.json
```
But when i try run gulp:
```
$ gulp
module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Volumes/LaCie/http/htdocs/mbootstrap.composer/vendor/mavenecommerce/mbootstrap/gulpfile.js:13:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

But it installed as local and global:
```
$ npm list --depth=0
mbootstrap@1.0.0 /Volumes/LaCie/http/htdocs/mbootstrap.composer/magento
├── del@1.2.0
├── gulp@3.9.0
├── ...
└── vinyl-paths@1.0.0

$ cd && gulp -v
[14:01:39] CLI version 3.8.11
```

So the probles with gulp because it doesn`t see himself via symlink by MCI. But if use modman only instead (with out composer) — everething is fine.

May be you can provide some idea to help to fix it...

Thanks

**Comment by Flyingmana** [comment]
I dont know what modman makes different here, it does only symlink too, right?

You could change your config to do copy, you can do this also for single packages if needed as described here: https://github.com/Cotya/magento-composer-installer/blob/3.0/doc/Deploy.md#overwrite-deploy-method-per-module

does this help to workaround the problem?

**Comment by klierik** [comment]
I just found problem... The problem with gulp because i doesn't saw himself.
Lets see project_root folder:
```
.
├── composer.json
├── composer.lock
├── magento
├── node_modules
├── vagrant
└── vendor
```

Magento folder:
```
drwxr-x---@ 34 aleksej  staff   1.1K Jul  7 19:07 .
drwxr-xr-x  10 aleksej  staff   340B Jul  7 19:07 ..
lrwxr-xr-x   1 aleksej  staff    49B Jul  7 18:17 gulpconfig.js -> ../vendor/mavenecommerce/mbootstrap/gulpconfig.js
lrwxr-xr-x   1 aleksej  staff    47B Jul  7 18:17 gulpfile.js -> ../vendor/mavenecommerce/mbootstrap/gulpfile.js
lrwxr-xr-x   1 aleksej  staff    48B Jul  7 18:17 package.json -> ../vendor/mavenecommerce/mbootstrap/package.json
```

So real gulp file locate not in `magento/` folder. It in `vendor/` folder. This is a problem. 

To fix it u should move `node_modules/` folder to project_root/ or create symlink like that:

`$ ln -s ../node_modules node_modules` and we get:
```
drwxr-x---@ 34 aleksej  staff   1.1K Jul  7 19:07 .
drwxr-xr-x  10 aleksej  staff   340B Jul  7 19:07 ..
lrwxr-xr-x   1 aleksej  staff    49B Jul  7 18:17 gulpconfig.js -> ../vendor/mavenecommerce/mbootstrap/gulpconfig.js
lrwxr-xr-x   1 aleksej  staff    47B Jul  7 18:17 gulpfile.js -> ../vendor/mavenecommerce/mbootstrap/gulpfile.js
lrwxr-xr-x   1 aleksej  staff    15B Jul  7 19:07 node_modules -> ../node_modules
lrwxr-xr-x   1 aleksej  staff    48B Jul  7 18:17 package.json -> ../vendor/mavenecommerce/mbootstrap/package.json
```

Or full view:
```
.
├── composer.json
├── composer.lock
├── magento
│   ├── ...
│   ├── gulpconfig.js -> ../vendor/mavenecommerce/mbootstrap/gulpconfig.js
│   ├── gulpfile.js -> ../vendor/mavenecommerce/mbootstrap/gulpfile.js
│   ├── includes
│   ├── ...
│   ├── media
│   ├── node_modules -> ../node_modules
│   ├── package.json -> ../vendor/mavenecommerce/mbootstrap/package.json
│   ├── ...
│   └── var
├── node_modules
├── vagrant
└── vendor
```

Now it work fine.

PS: can you tell me please how correctly remove module? When i jut remove it from `composer.json` and run `composer update --no-plugins` in `magento/` folder all symlinks still leave. But they are should be removed, yeas?!

**Comment by AydinHassan** [comment]
@klierik don't run it with `--no-plugins`.  That disables this plugin from working hence why it isn't removing symlinks.

**Comment by beejhuff** [comment]
On Wednesday, July 8, 2015, Aydin Hassan <notifications@github.com> wrote:

> @klierik <https://github.com/klierik> don't run it with --no-plugins.
> That disables this plugin from working hence why it isn't removing
> symlinks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cotya/magento-composer-installer/issues/39#issuecomment-119543482>
> .
>


-- 
Sent from Gmail Mobile

**Comment by klierik** [comment]
Okay, with out `--no-plugins`:
```
$ composer update
you may want to add the packages.firegento.com repository to composer.
add it with: composer.phar config -g repositories.firegento composer http://packages.firegento.com
you may want to add the packages.magento.com repository to composer.
add it with: composer.phar config -g repositories.magento composer https?://packages.magento.com
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing magento-hackathon/magento-composer-installer (3.0.2)
  - Removing eloquent/composer-config-reader (2.0.0)
  - Removing eloquent/enumeration (5.1.0)
  - Removing eloquent/liberator (1.1.1)
  - Removing eloquent/pops (3.1.1)
  - Removing icecave/isolator (2.3.0)
  - Removing justinrainbow/json-schema (1.4.2)
  - Removing symfony/console (v2.7.1)
  - Removing twbs/bootstrap-sass (v3.3.5)
  - Removing mavenecommerce/mbootstrap (dev-mbootstrap_sass_composer)
Generating autoload files

Fatal error: Class 'MagentoHackathon\Composer\Helper' not found in /Volumes/LaCie/http/htdocs/mbootstrap.composer/vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php on line 211
```

Then:
```
$ l magento/
total 1376
drwxr-x---@ 34 aleksej  staff   1.1K Jul  7 19:07 .
drwxr-xr-x   9 aleksej  staff   306B Jul  8 16:25 ..
...
lrwxr-xr-x   1 aleksej  staff    49B Jul  7 18:17 gulpconfig.js -> ../vendor/mavenecommerce/mbootstrap/gulpconfig.js
lrwxr-xr-x   1 aleksej  staff    47B Jul  7 18:17 gulpfile.js -> ../vendor/mavenecommerce/mbootstrap/gulpfile.js
...
lrwxr-xr-x   1 aleksej  staff    15B Jul  7 19:07 node_modules -> ../node_modules
lrwxr-xr-x   1 aleksej  staff    48B Jul  7 18:17 package.json -> ../vendor/mavenecommerce/mbootstrap/package.json
```
And:
```
$ l vendor/
total 16
drwxr-xr-x  6 aleksej  staff   204B Jul  8 16:25 .
drwxr-xr-x  9 aleksej  staff   306B Jul  8 16:25 ..
-rw-r--r--  1 aleksej  staff   183B Jul  8 16:25 autoload.php
drwxr-xr-x  2 aleksej  staff    68B Jul  8 16:25 bin
drwxr-xr-x  8 aleksej  staff   272B Jul  7 18:17 composer
-rw-r--r--  1 aleksej  staff   428B Jul  7 18:17 installed.json
```

So module removed but it do not clean nothing :(

**Comment by Flyingmana** [comment]
You have to keep the installer till you removed all magento modules, you cant them remove all at once without error.

So first remove modules, not installer, with active plugins.

Then remove installer with disabled plugins

**Comment by klierik** [comment]
Thanks you for reply!

My Composer Module require:
```
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.firegento.com"
        },
        {
            "type": "composer",
            "url": "https?://packages.magento.com"
        }
    ],
    "require": {
        "magento-hackathon/magento-composer-installer": "3.0.2",
        "twbs/bootstrap-sass": "*"
    },
    "extra": {
        "magento-root-dir": "magento/",
        "magento-force": true
    }
```

When someone add my module to own project he add:
```
    "repositories": {
        "mbootstrap": {
            "type": "vcs",
            "url": "git@github.com:mavenecommerce/mbootstrap.git"
        }
    },
    "require": {
        "mavenecommerce/mbootstrap": "dev-master"
    },
    "extra": {
        "magento-root-dir": "magento"
    }
```

So, when somebody add my module it dependence MCI. When module should be removed this source need to be removed from `composer.json`.

I think i'm wrong somewhere but i don`t understand where :( I'm not correctly using MCI module?
May be it should be added with my module, not like dependence in my module? Like:
```
    "repositories": {
        "mbootstrap": {
            "type": "vcs",
            "url": "git@github.com:mavenecommerce/mbootstrap.git"
        },
        {
            "type": "composer",
            "url": "http://packages.firegento.com"
        },
    },
    "require": {
        "magento-hackathon/magento-composer-installer": "3.0.2",
        "mavenecommerce/mbootstrap": "dev-master"
    },
    "extra": {
        "magento-root-dir": "magento/",
        "magento-force": true
    }
```

**Comment by klierik** [comment]
i have try install MCI and my module separated:
```
    "require": {
        "magento-hackathon/magento-composer-installer":"*",
        "mavenecommerce/mbootstrap": "dev-master"
    },
```

then i remove my module:
```
    "require": {
        "magento-hackathon/magento-composer-installer":"*"
    },
```

and run:
```
$ composer update --no-plugins
Loading composer repositories with package information
Updating dependencies (including require-dev)                                
  - Removing twbs/bootstrap-sass (v3.3.5)
  - Removing mavenecommerce/mbootstrap (dev-master)
Writing lock file
Generating autoload files
```
But nothing change:
```
lrwxr-xr-x   1 aleksej  staff    49B Jul  9 18:10 gulpconfig.js -> ../vendor/mavenecommerce/mbootstrap/gulpconfig.js
lrwxr-xr-x   1 aleksej  staff    47B Jul  9 18:10 gulpfile.js -> ../vendor/mavenecommerce/mbootstrap/gulpfile.js
lrwxr-xr-x   1 aleksej  staff    48B Jul  9 18:10 package.json -> ../vendor/mavenecommerce/mbootstrap/package.json
```

Can you tell me please what i need todo to tell MCI remove all installed modules?

**Comment by AydinHassan** [comment]
@klierik  `composer update --no-plugins` 

do not run with `--no-plugins`

why are you running with that?

**Comment by klierik** [comment]
I don't know... I saw it somewhere and just trying.
There is no any information how to uninstall plugins here: https://github.com/Cotya/magento-composer-installer
So i just trying all possible variants that i know/saw in internet :)

**Comment by AydinHassan** [comment]
MCI is a composer plugin. If you run with `--no-plugins` this plugin will not run. The code which removes module is contained within this plugin. So you need to run composer update WITH plugins. So after you have removed the modules from your `composer.json` just run `composer update` :)

**Comment by klierik** [comment]
okay. Fresh Magento 1.9.1.0 + sample install. Removed vendor/ and composer.lock

composer.json
```
    "require": {
        "magento-hackathon/magento-composer-installer":"*",
        "mavenecommerce/mbootstrap": "dev-master"
    },
```

then:
```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)                              
  - Installing twbs/bootstrap-sass (v3.3.5)
    Loading from cache

  - Installing mavenecommerce/mbootstrap (dev-master 7c70697)
    Cloning 7c70697d0e75950f5096b42bee804ec381cba6fe

  - Installing symfony/console (v2.7.1)
    Loading from cache

  - Installing justinrainbow/json-schema (1.4.2)
    Loading from cache

  - Installing icecave/isolator (2.3.0)
    Loading from cache

  - Installing eloquent/pops (3.1.1)
    Loading from cache

  - Installing eloquent/liberator (1.1.1)
    Loading from cache

  - Installing eloquent/enumeration (5.1.0)
    Loading from cache

  - Installing eloquent/composer-config-reader (2.0.0)
    Loading from cache

  - Installing magento-hackathon/magento-composer-installer (3.0.3)
    Loading from cache

you may want to add the packages.magento.com repository to composer.
add it with: composer.phar config -g repositories.magento composer https?://packages.magento.com
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
symfony/console suggests installing psr/log (For using the console logger)
icecave/isolator suggests installing eloquent/asplode (Drop-in exception-based error handling.)
magento-hackathon/magento-composer-installer suggests installing colinmollenhour/modman (*)
magento-hackathon/magento-composer-installer suggests installing theseer/autoload (~1.14)
Writing lock file
Generating autoload files
Autoloader patch to magento/app/Mage.php was applied successfully
```

everything is fine — MCI created symlinks.

then i remove entry from composer.json:
```
"require": {
        "magento-hackathon/magento-composer-installer":"*"
    },
```

and run `composer update`:
```
$ composer update
you may want to add the packages.magento.com repository to composer.
add it with: composer.phar config -g repositories.magento composer https?://packages.magento.com
Loading composer repositories with package information
Updating dependencies (including require-dev)                                
  - Removing twbs/bootstrap-sass (v3.3.5)
  - Removing mavenecommerce/mbootstrap (dev-master)
Writing lock file
Generating autoload files
magento/app/Mage.php was already patched
```

and check magento/ folder:
```
$ l magento/
total 1368
drwxr-x---@ 33 aleksej  staff   1.1K Jul  9 19:02 .
drwxr-xr-x   9 aleksej  staff   306B Jul  9 19:04 ..
-rw-r-----   1 aleksej  staff   5.5K Apr 28 14:03 .htaccess
lrwxr-xr-x   1 aleksej  staff    49B Jul  9 19:02 gulpconfig.js -> ../vendor/mavenecommerce/mbootstrap/gulpconfig.js
lrwxr-xr-x   1 aleksej  staff    47B Jul  9 19:02 gulpfile.js -> ../vendor/mavenecommerce/mbootstrap/gulpfile.js
drwxr-x---@  4 aleksej  staff   136B Apr 28 14:03 includes
lrwxr-xr-x   1 aleksej  staff    48B Jul  9 19:02 package.json -> ../vendor/mavenecommerce/mbootstrap/package.json
-rw-r-----   1 aleksej  staff   886B Apr 28 14:03 php.ini.sample
drwxr-x---@  5 aleksej  staff   170B Apr 28 14:15 pkginfo
drwxr-x---@  6 aleksej  staff   204B Apr 28 14:15 shell
drwxr-x---@  5 aleksej  staff   170B Jul  9 19:01 skin
drwxr-x---@  6 aleksej  staff   204B Jul  9 19:00 var
```

Tell me please — what i`m doing wrong?

**Comment by AydinHassan** [comment]
@klierik Maybe a bug, i'll try test it later or tomorrow morning. But the process you just followed should work.

**Comment by klierik** [comment]
@AydinHassan thanks you a lot.
PS: yesterday i try magento 1.9.2.0 fresh install + sample. after that i install only MCI via composer — result: white page

Server: Ubuntu vagrant
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
```

**Comment by Flyingmana** [comment]
thank you for reporting, the bug is reproducable and will get fixed for the next release
